# Generated by Django 4.2.1 on 2023-05-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('nivel_agua', models.FloatField()),
                ('ph', models.FloatField()),
                ('capacidad_maxima', models.FloatField()),
                ('temperatura_agua', models.FloatField()),
                ('fecha_ultima_revision', models.DateField()),
            ],
        ),
    ]
